stages:
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build

check:
  stage: test
  image: eclipse-temurin:21-jdk
  tags:
    - shared  # 替换为你的 Runner 实际标签
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
  script:
    - ./gradlew test
