GET http://localhost:8888/api/config
Accept: application/json

###
POST http://localhost:8888/api/config
Content-Type: application/json

{
  "port": 7070,
  "index": "/web/",
  "ssl": {
    "use": false,
    "certPath": null,
    "keyPath": null
  },
  "login": {
    "path": "/api/sso/login",
    "page": "/web/login",
    "api": "http://127.0.0.1:8080/api/sso/login"
  },
  "jwt": {
    "use": true,
    "checkExpiration": false,
    "expiresMin": null
  },
  "session": {
    "use": true,
    "timeoutHour": 24
  },
  "redirects": [
    {
      "from": "/api/sso/logout",
      "to": "/logout"
    }
  ],
  "frontends": [
    {
      "path": "/web",
      "dir": "/Users/aruis/develop/workspace-bsy/unicom_xinan_project/dist",
      "notFoundReroute": "/",
      "secured": true,
      "regex": false,
      "comment": null,
      "noCache": [
        "/",
        "/index.html"
      ],
      "allowlist": [
        ".*\\..*",
        "/login"
      ]
    }
  ],
  "upstreams": [
    {
      "path": "/api",
      "secured": true,
      "regex": false,
      "comment": null,
      "noCache": [],
      "allowlist": [
        "/sso/kaptcha",
        "/platform/conf/get"
      ],
      "backends": [
        {
          "url": "http://127.0.0.1:8080/api/",
          "weight": 1
        }
      ]
    }
  ]
}

###
